- name: create package directory
  file:
    path: "{{ rock_cache_dir }}/Packages"
    state: "directory"

- name: render template
  template:
    src: "{{ role_path }}/templates/rock-offline.j2"
    dest: "/tmp/rock-offline.conf"

- name: download packages
  repobuilder:
    packages: "{{ download_packages }}"
    groups: "{{ package_groups }}"
    config: "/tmp/rock-offline.conf"
    download_path: "{{ rock_cache_dir }}/Packages"
    exclude: "i686"
    tempcache: true

- name: gather list of rpms to Sign
  find:
    paths:
      - "{{ rock_cache_dir }}/Packages"
    patterns: "*.rpm"
    file_type: "file"
  register: find_result
  when: (skip_gpg == 'false')

- name: Signing packages
  rpmsign:
    rpms: "{{ find_result.files | map(attribute='path') | list }}"
    passphrase: "{{ gpg_passphrase }}"
    key: "{{  gpg_key_name }}"
    macros: "{{ gpg_macros }}"
  no_log: true
  when: (skip_gpg == 'false')

- name: clear old repo data
  file:
    state: absent
    path: "{{ rock_cache_dir }}/repodata"

- name: generate fresh repo data
  command: createrepo_c "{{ rock_cache_dir | quote }}"

- name: create support directory
  file:
    path: "{{ rock_cache_dir }}/support"
    state: "directory"

- name: download ET Suricata rules
  get_url:
    url: https://rules.emergingthreats.net/open/suricata-4.0/emerging.rules.tar.gz
    checksum: "md5:https://rules.emergingthreats.net/open/suricata-4.0/emerging.rules.tar.gz.md5"
    dest: "{{ rock_cache_dir }}/support/emerging.rules-suricata.tar.gz"
    mode: 0644

- name: download RockNSM scripts
  get_url:
    url: https://github.com/rocknsm/rock-scripts/archive/{{ rockscripts_branch }}.tar.gz
    dest: "{{ rock_cache_dir }}/support/rock-scripts_{{ rockscripts_branch }}.tar.gz"
    mode: 0644

- name: download RockNSM dashboards
  get_url:
    url: https://github.com/rocknsm/rock-dashboards/archive/{{ rockdashboards_branch }}.tar.gz
    dest: "{{ rock_cache_dir }}/support/rock-dashboards_{{ rockdashboards_branch }}.tar.gz"
    mode: 0644

- name: sign all the things
  command: "gpg2 --detach-sign --yes --armor --passphrase {{ gpg_passphrase }} --batch -u security@rocknsm.io {{ item | quote }}"
  with_items:
    - "{{ rock_cache_dir }}/repodata/repomd.xml"
    - "{{ rock_cache_dir }}/support/emerging.rules-suricata.tar.gz"
    - "{{ rock_cache_dir }}/support/rock-scripts_{{ rockscripts_branch }}.tar.gz"
    - "{{ rock_cache_dir }}/support/rock-dashboards_{{ rockdashboards_branch }}.tar.gz"
  when: (skip_gpg == 'false')
  no_log: true
