---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: rock-createiso-git
    type: git
    source:
      uri: https://github.com/rocknsm/rock-createiso.git
      branch: master

  - name: rocknsm-slack
    type: slack-notification
    source:
      url: ((slack-webhook))

jobs:
  - name: rocknsm-create-iso
    build_logs_to_retain: 14
    serial: true
    plan:
      - get: rock-createiso-git
      - task: download-centos-minimal-iso
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: centos, tag: 7 }
          inputs:
            - name: rock-createiso-git
          outputs:
            - name: centos-minimal-iso
          run:
            path: /bin/bash
            args:
              - '-c'
              - 'rock-createiso-git/concourse/download_minimal_iso.sh "$MIRROR_HOST"'
          params:
            MIRROR_HOST: ((mirror-host))
        on_failure:
          put: rocknsm-slack
          params:
            text: "Concourse Pre-Release failed to build. Could not retrieve a copy of centos minimal iso."
            username: "Concourse-CI"
            # icon_url: URL

      - task: rock-create-iso
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: centos, tag: 7 }
          inputs:
            - name: rock-createiso-git
            - name: centos-minimal-iso
          outputs:
            - name: rocknsm-iso
          run:
            path: /bin/bash
            args:
              - '-c'
              - 'rock-createiso-git/concourse/create_iso.sh "$GPG_KEY_NAME" "$GPG_KEY_PASS" "$GPG_KEY" "$ENABLE_TESTING" "OFFICIAL_RELEASE" "$PULP_HOST"'
          params:
            GPG_KEY: ((gpg-key))
            GPG_KEY_PASS: ((gpg-passphrase))
            GPG_KEY_NAME: ((gpg-key-name))
            ENABLE_TESTING: 0
            OFFICIAL_RELEASE: 0
            PULP_HOST: ((pulp-host))
        on_failure:
          put: rocknsm-slack
          params:
            text: "Concourse Pre-Release Failed to build. Task: rock-create-iso. Check webui for additional information."
            username: "Concourse-CI"
            # icon_url: URL
      - task: upload-iso
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: centos, tag: 7 }
          inputs:
            - name: rocknsm-iso
            - name: rock-createiso-git
          run:
            path: /bin/bash
            args:
              - '-c'
              - 'rock-createiso-git/concourse/upload.sh "$MIRROR_USER" "$MIRROR_PASS" "$MIRROR_HOST" "$MIRROR_REPO" "$MIRROR_PRIVATE" "$MIRROR_PUBLIC" "$MIRROR_IP"'
          params:
            MIRROR_USER: ((mirror-user))
            MIRROR_PASS: ((mirror-pass))
            MIRROR_HOST: ((mirror-host))
            MIRROR_REPO: "prerelease"
            MIRROR_PRIVATE: ((mirror-private-key))
            MIRROR_PUBLIC: ((mirror-public-key))
            MIRROR_IP: ((mirror-ip))
        on_failure:
          put: rocknsm-slack
          params:
            text: "Concourse Pre-Release Failed to upload ISO to mirror. Check webui for additional information."
            username: "Concourse-CI"
        on_success:
          put: rocknsm-slack
          params:
            text: "Concourse Pre-Release build successful. The release build can be found here <((mirror-uri))|Pre-Release>"
            username: "Concourse-CI"
