---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: rock-createiso-git
  type: git
  source:
    uri: https://github.com/rocknsm/rock-createiso.git
    branch: master

- name: RockNSM-Slack
  type: slack-notification
  source:
    url: ((slack-webhook))

- name: Nightly-Timer
  type: time
  source:
    start: 8:00 AM
    stop: 8:15 AM

jobs:
- name: RockNSM Create ISO
  build_logs_to_retain: 14
  serial: true
  plan:
  - get: rock-createiso-git
  - get: Nightly-Timer
    trigger: true
  - task: Download centOS Minimal ISO
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: centos }
      inputs:
        - name: rock-createiso-git
      outputs:
        - name: centos-minimal-iso
      run:
        path: /bin/bash
        args:
          - '-c'
          - 'rock-createiso-git/concourse/download_minimal_iso.sh "$MIRROR_HOST"'
      params:
        MIRROR_HOST: ((mirror-host))
    on_failure:
      put: RockNSM-Slack
      params:
        text: "Concourse Nightly failed to build. Could not retrieve a copy of centos minimal iso."
        username: "Concourse-CI"
        # icon_url: URL

  - task: ROCK Create ISO
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: centos }
      inputs:
        - name: rock-createiso-git
        - name: centos-minimal-iso
      outputs:
        - name: rocknsm-iso
      run:
        path: /bin/bash
        args:
          - '-c'
          - 'rock-createiso-git/concourse/create_iso.sh "$GPG_KEY_NAME" "$GPG_KEY_PASS" "$GPG_KEY" "$ENABLE_TESTING" "$OFFICIAL_RELEASE"'
      params:
        GPG_KEY: ((gpg-key))
        GPG_KEY_PASS: ((gpg-passphrase))
        GPG_KEY_NAME: ((gpg-key-name))
        ENABLE_TESTING: 1
        OFFICIAL_RELEASE: 0
    on_failure:
      put: RockNSM-Slack
      params:
        text: "Concourse Nightly Failed to build. Task: ROCK Create ISO. Check webui for additional information."
        username: "Concourse-CI"
        # icon_url: URL
  - task: Upload ISO
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: centos }
      inputs:
        - name: rock-createiso-git
        - name: rocknsm-iso
      run:
        path: /bin/bash
        args:
          - '-c'
          - 'rock-createiso-git/concourse/upload.sh "$MIRROR_USER" "$MIRROR_PASS" "$MIRROR_HOST" "$MIRROR_REPO" "$MIRROR_PRIVATE" "$MIRROR_PUBLIC"'
      params:
        MIRROR_USER: ((mirror-user))
        MIRROR_PASS: ((mirror-pass))
        MIRROR_HOST: ((mirror-host))
        MIRROR_REPO: "testing"
        MIRROR_PRIVATE: ((mirror-private-key))
        MIRROR_PUBLIC: ((mirror-public-key))
    on_failure:
      put: RockNSM-Slack
      params:
        text: "Concourse Nightly Release Failed to upload ISO to mirror. Check webui for additional information."
        username: "Concourse-CI"
    on_success:
      put: RockNSM-Slack
      params:
        text: "Concourse Nightly Release build successful. The prerelease build can be found here <((mirror-uri))|Nightly Release>"
        username: "Concourse-CI"
